### PR TITLE
Discover code

### PR DESCRIPTION
**Pull request by montassarelbehi**

### CODE REVIEW

**Comment by yesbutno** [comment]
I don't think it is a good idea to introduce a separate Constants class. Constants should be declared in the context they have a meaning in and are used.
With a separate class, we'd group together totally unrelated elements into a single class.
And while we're at it, we could convert related constants to enums that can be located either within the class (if they make sense only there) or within the same package.

**Comment by anaili** [comment]
I totally agree, creating a package just for enums is a bad design as well. Other developers can't even figure out where to use what and maybe we'll run into conflicts of constants.

**Comment by yesbutno** [comment]
Well then, what do we do? We can't just change it back and forth, can we?

**Comment by anaili** [comment]
Yes we can rollback the commit, but I suggest to consider this pr as an uncompleted task and we let @montassarelbehi do more work on this. what do you think ?

**Comment by bessemHmidi** [comment]
yes, i agree with anaili.

**Comment by yesbutno** [comment]
Sounds good.

**Pull request merged**
