### PR TITLE
Changed the way of counting the parameters in CommonUtils.java class for better performance.

### PR DESCRIPTION
**Pull request by osnimarin**
Changed the way of counting the parameters in CommonUtils.java class for better performance.
Class HalfDuplexEndPoint.java, changed the parameter of urlPatterns WebServlet annotation to use the Constants.URL_PATTERNS.

### CODE REVIEW

**Review by bessemHmidi — COMMENTED** [review]
i think it would be better to move URL_PATTERNS to the ceoncerning class : 
to obtain:
HalfDuplexEndPoint.URL_PATTERNS

**Comment by yesbutno** [comment]
Will this constant be used in any other context than this class? I mean, is there already some second use case for it?

**Comment by osnimarin** [comment]
@WebFilter(asyncSupported = true, urlPatterns = Constants.URL_PATTERNS)
public class NGFilter implements Filter { ...

In this case it is possible to intercept all actions of the servlet!!!

**Comment by osnimarin** [comment]
good idea, I'll Change to the HalfDuplexEndPoint.

**Comment by osnimarin** [comment]
Testing this change, she created a problem because the class has injections and this made the class to instantiate more than once, so I had to leave in the constants.

**Pull request closed without merging**
