### PR TITLE
* remove enums package.

### PR DESCRIPTION
**Pull request by montassarelbehi**
Waiting for your feedback to continue work on it. What about duplicated Callback and What about util constants? Thaks!

### CODE REVIEW

**Comment by yesbutno** [comment]
As I see it the `enum Callback` is only used as an argument to the `@Eval` annotation so I would place its declaration _within_ the annotation. And then you could also replace the `if - else` in `ModuleGenerator`with a `switch - case`.

**Comment by yesbutno** [comment]
The constants can be divided into three groups:
- HTTP methods
  I would create an `enum` and place it in the `angularBeans.api.http` package.
- Constants for names/identifiers of getters and setters
  They are part of the concept "JavaBeans" which is handled in the class with the misleading name `CommonUtils`. So an `enum` for them, and the class maybe renamed to `JavaBeans`.
- The rest
  - I don't really see the advantage of having constants for TWO and THREE.
  - NG_SESSION_ATTRIBUTE_NAME could be moved to angularBeans.context.MainHTTPSessionListener

**Comment by montassarelbehi** [comment]
+1 good idea to use enum.

According to constants, I just took the habit :) This is called magic number: is a direct usage of a number in the code. To refactor it makes the code easier to maintain and can improves its readability!
In addition, the JDK is full of examples like Integer.MAXSIZE, BigDecimal.ONE and many other classes.
Finally, analysis tools like FindBugs, SonarQube and PMD detects the use of magic numbers in your code and suggests the refactoring.

**Comment by yesbutno** [comment]
Agreed. Only ONE and TWO I wouldn't see as magic numbers. The get/set/is should be placed into an `enum` _inside_ the `CommonUtils` (or maybe `JavaBeans`?) class.

**Pull request closed without merging**
