### PR TITLE
Close inputstream

### PR DESCRIPTION
**Pull request by tiagodev**
forgot to close it

### CODE REVIEW

**Comment by yesbutno** [comment]
But you're loading the whole file on every call to getProperty(). Is this intentionally? (I have to ask because I don't fully understand the purpose of this class yet.)

**Comment by tiagodev** [comment]
Right now it only runs once and only on initJsonSerialiser(), which also only runs once. But you're right, i could probably change that.
The purpose is to have some place where i can configure AngularBeans. At the moment i'm using it to pass an exclusion strategy class to GsonBuilder.

GsonBuilder builder = new GsonBuilder().serializeNulls();
builder.setExclusionStrategies(NGConfiguration.getGsonExclusionStrategy());

**Comment by osnimarin** [comment]
good afternoon,

I'm trying to use the ng.properties you created, because as I'm trying to pass some parameters to use in initJsonSerialiser to work as dates in standard UTC. Could you help me with a example?

**Comment by tiagodev** [comment]
It's pretty simple,
1. Create the ng.properties in the src/main/resources of the web project.
2. On initJsonSerialiser use NGConfiguration.getProperty("property") and do whatever you need with the value

**Comment by osnimarin** [comment]
Are you Brazilian?

**Comment by tiagodev** [comment]
portuguese

**Comment by osnimarin** [comment]
Then, you must have the same problem as us in a matter of date and timezone

**Comment by osnimarin** [comment]
Do not break the norm, I need something like:
DATE_FORMAT = UTC
TIME_ZONE = GMT

It would be something like you would use?

**Comment by tiagodev** [comment]
i haven't come up with any problems with dates yet but it would be good to have those options available

**Comment by osnimarin** [comment]
We are building an ERP with AngularBeans and EJB3, and we are facing some difficulties, mainly date because the EJB has 3 types and this generates conversion error. So the solution was to generate all in UTC format both on the way to the JS and in back. So I need the parameter, not to change who is using different.

**Pull request merged**
